set windows-shell := ["C:\\Program Files\\Git\\bin\\sh.exe","-c"]
set export := true
set positional-arguments := true

user := file_stem(home_directory())
curr_time := datetime("%Y%m%dT%H%M%S")

# Open the devenv shell
shell:
    {{ if env("DEVENV_RUNTIME", "") == "" { "sudo -E devenv shell --impure --verbose" } else { "echo 'Already in devenv shell!'" } }}

# Own the current directory as the logged in user
own:
    sudo chown -R {{ user }} .

# Initialize the python project environment
ready-py:
    uv sync --all-extras --all-groups

# Run the app using the Python runtime
run: ready-py
    flet run

# Build the app
build platform: ready-py
    flet build {{ platform }} -vv