site_name: Flet-Easy
site_url: https://daxexs.github.io/flet-easy/
site_author: Daxexs
site_description: >-
  Flet-Easy is a user-friendly add-on package for Flet, offering a cleaner code structure with numerous customizable features.
edit_uri: edit/main/docs/
copyright: Copyright &copy; 2024 Daxexs
repo_name: Daxexs/flet-easy
repo_url: https://github.com/Daxexs/flet-easy

theme:
  custom_dir: docs/overrides
  name: material
  palette:
    - media: "(prefers-color-scheme)"
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  font:
    text: Lexend
    code: Fira Code
    font: false
  language: en
  direction: ltr
  logo: assets/images/logo.png
  favicon: assets/images/favicon.png
  icon:
    edit: material/pencil-remove-outline
    view: material/eye
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.tracking
    - navigation.path
    - navigation.indexes
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - navigation.footer
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - content.action.edit

plugins:
  - tags:
      tags_allowed:
        - flet
        - flet easy
        - flet router
        - flet middleware
        - flet jwt
        - flet cli
        - flet decorators
        - dynamic routing
        - async support
        - page 404
        - route protection
        - data sharing
        - responsive design
        - flet events
        - flet integration

  - search:
      lang:
        - en
        - es
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
      pipeline:
        - stemmer
        - stopWordFilter
        - trimmer

extra_css:
  - stylesheets/extra.css

extra:
  status:
    new: Recently added
    deprecated: Deprecated
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Daxexs/flet-easy
      name: Repository
  generator: false

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - attr_list
  - md_in_html
  - toc:
      permalink: true

nav:
  - index.md
  - installation.md
  - begin.md
  - how-to-use.md
  - run-the-app.md
  - cli-to-create-app.md
  - data-sharing-between-pages.md
  - dynamic-routes.md
  - Add pages:
      - Through decorators: add-pages/through-decorators.md
      - By means of functions: add-pages/by-means-of-functions.md
      - Through classes: add-pages/through-classes.md
      - In automatic: add-pages/in-automatic.md
  - Customized app:
      - Route protection: customized-app/route-protection.md
      - General settings: customized-app/general-settings.md
      - control view configuration: customized-app/control-view-configuration.md
      - Page 404: customized-app/page-404.md
      - events: customized-app/events.md
  - Events:
      - On keyboard event: events/keyboard-event.md
      - On resize: events/on-resize.md
  - middleware.md
  - basic-jwt.md
  - ref.md
  - responsiveControlsy.md
  - working-with-other-apps.md
