""" No decorators """
#from .index import index_page
#from .test import test_page
#from .counter import counter_page
#from .login import login_page
#from .task import task_page
#from .mardown import markdown_page
#from .response import response_page
#from .on_keyboard import keyboard_page

""" With decorators """
from .counter import counter
from .index import index
from .login import login
from .markdown import markdown
from .on_keyboard import keyboard
from .response import response
from .task import task
from .test import test
from .pubsub import pbs
