[project]
name = "flet-app"
version = "0.1.0"
license = "MIT"
dependencies = [
    "flet==0.83.*",
    "flet-easy[jwt]==0.3.0.dev26",
    "tortoise-orm==0.22.2",
]

[[project.authors]]
name = "Daxexs"
email = "Daxexs@test.com"

[tool.flet]
org = "com.mycompany"                         # --org
product = "flet-easy"                         # --product
company = "My Company"                        # --company
copyright = "Copyright (C) 2026 by MyCompany" # --copyright
build_number = 1                              # --build-number
BUILD_VERSION = "0.2.0"

[tool.flet.app]
path = "src"

[tool.flet.compile]
app = true
packages = true

[tool.flet.splash]
color = ""      # --splash-color
dark_color = "" # --splash-dark-color
web = false     # --no-web-splash
ios = false     # --no-ios-splash
android = true  # --no-android-splash

[tool.flet.cleanup] # or [tool.flet.<PLATFORM>.cleanup]
app = true
packages = true
app_files = ["**/*.c", "**/*.h"]
package_files = ["**/*.pyi"]
