name: Linters

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  linters:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout Repository
          uses: actions/checkout@v4
  
        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: "3.12"

        - name: Install the latest version of uv and enable caching and define a custom cache key suffix
          id: setup-uv
          uses: astral-sh/setup-uv@v5
          with:
            version: "latest"
            enable-cache: true
            cache-suffix: "optional-suffix"
      
  
        - name: Install dependencies
          run: uv sync --all-extras --all-groups 
  
        - name: Run Ruff - Mode Check
          run: |
              uv run ruff check .
              echo "Ruff check completed"
  
        - name: Run Ruff - Mode Format
          run: |
              uv run ruff format.
              echo "Ruff format check completed"

        - name: Markdown Lint install
          uses: DavidAnson/markdownlint-cli2-action@v19
          with:
            config: .markdownlint.yaml
            globs: |
              README.md
              CHANGELOG.md
              CONTRIBUTING.md
              docs/*.md
              tests/*.md