name: Tests

on:
  push:
    paths:
      - "tests/*"
      - "tests/ui/*"
      - "src/**"
      - ".github/workflows/tests.yml"
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  tests:
    strategy:
      matrix:
        python-version: ["3.9", "3.12"]
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install the latest version of uv and enable caching and define a custom cache key suffix
        id: setup-uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "latest"
          enable-cache: true
          cache-suffix: "optional-suffix"

      - name: syncronize flet-easy
        run: |
          uv sync --all-groups --all-extras
          echo "Syncronize flet-easy completed"

      - name: Run tests via nox
        run: uv run nox -s tests_scripts tests_scripts_ui --python ${{ matrix.python-version }}

